Node Classification in SIMP
---------------------------

From the Puppet, Inc. website:

  Hiera is a key/value lookup tool for configuration data, built to set
  node-specific data without repeating yourself.

SIMP uses :term:`Hiera` to attempt to make configuration of the overall system easier
for our end users by providing a simple, centralized, method for setting class
parameters using `automatic parameter lookup`_.

It is **highly recommended** that you read the `Hiera Documentation`_ prior to
jumping into using a SIMP system.

.. _Hiera Documentation: https://puppet.com/docs/puppet/5.5/hiera.html
.. _automatic parameter lookup: https://puppet.com/docs/puppet/5.5/hiera_automatic.html#looking-up-data-with-hiera
